[[redirects]]
  from = "adamgoodcoder.com/*"
  to = "codedbyadam.com/:splat"
  status = 301
  force = false

  [[redirects]]
  from = "https://adamgoodcoder.com/*"
  to = "https://codedbyadam.com/:splat"
  status = 301
  force = true